esphome:
  name: fujitsu
  platform: esp32
  board: esp32-c3-devkitm-1
  includes:
    - src/FujitsuClimate.h
    - src/FujitsuClimate.cpp
    - src/FujiHeatPump.h
    - src/FujiHeatPump.cpp
  platformio_options:
    build_flags:
      -D ARDUINO_USB_MODE=1
      -D ARDUINO_USB_CDC_ON_BOOT=1
      -D ARDUINO_ESP32C3_DEV=1

# Enable logging
logger:
  baud_rate: 0
  level: DEBUG

# Enable Home Assistant API
api:
  password: ""

web_server:
  port: 80

ota:
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fujitsu"
    password: "a fancy password"


captive_portal:

climate:
- platform: custom
  lambda: |-
    auto fujitsuClimate = new fujitsu::FujitsuClimate();
    App.register_component(fujitsuClimate);
    return {fujitsuClimate};

  climates:
    - name: "Fujitsu"
